lucky_numbers = [4, 8, 15, 16, 23, 42]
friends = ["Rachel", "Rafael", "Terry", "Curt", "Curt", "Kevin"]
#friends.extend(lucky_numbers)
#friends.append("Creed")
#friends.insert(3, "Bob")
#friends.remove("Kevin")
#friends.clear()
#friends.pop()
#print(friends.index("Kevin"))
#friends.sort()
#lucky_numbers.reverse()
#lucky_numbers.sort()
#print(lucky_numbers)
#print(friends)
#print(friends.count("Curt"))
friends2 = friends.copy()
print(friends2)